version: "1"

services:
  database:
    build: ./db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: 0.0.0.0
      MYSQL_USER: utente
      MYSQL_PASSWORD: password
      MYSQL_DB: portale
    volumes:
      - ./db/init_scripts:/docker-entrypoint-initdb.d/
  app:
    depends_on:
        - database
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
