CREATE DATABASE /*!32312 IF NOT EXISTS*/ `portale` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
CREATE USER IF NOT EXISTS 'utente'@'%' IDENTIFIED BY 'password';
USE `portale`;
GRANT ALL PRIVILEGES ON portale.* TO 'utente'@'%';